ansible all -m  setup | grep ansible_distribution # Command
---
- name: updating system
  hosts: all
  become: yes
  tasks:
  - name: updating
    command: yum update -y
    when: ansible_distribution == "Amazon"

  - name: updating ubuntu system
    command: apt update -y
    when: ansible_distribution == "Ubuntu"
